TMM: Add tables for map pools
FAForever/db pull request #214
Opened 2020-03-15 07:55 UTC by Askaholic

For team matchmaking we need to be able to support multiple map pools. This PR adds the ability to create any number of map pools, and set one map pool as the active one for each matchmaker pool. 

Things I'd like some feedback on:
- Should we add a description to map_pool? I'm imagining that the name/description of map pools will only serve as a tool to help the admins remember what the map pool was designed for and will never be shown to regular users.
- Should map_pools_maps many-to-many table have create/update time? I'm thinking that's probably too much data which will have little value.

2020-03-15 09:02 UTC, Geosearchef commented
That's not the way we want to implement map pools. As I told you, can we please first talk about this?

2020-03-15 14:01 UTC, norraxx commented on migrations/V82__map_pools.sql
> +) COMMENT="A collection of maps, used by a matchmaker for map selection";
engine=innodb

2020-03-15 14:01 UTC, norraxx commented on migrations/V82__map_pools.sql
> +    PRIMARY KEY (map_pool_id, map_id)
add `key (map_id, map_pool_id)`

2020-03-15 14:01 UTC, norraxx commented on migrations/V82__map_pools.sql
> +) COMMENT="A collection of maps, used by a matchmaker for map selection";
why do we have such `create_time` and `update_time`? If we will filter/search by this values, we should add indexes now. Otherwise it will be pain.

2020-03-15 18:23 UTC, Askaholic commented on migrations/V82__map_pools.sql
> +    PRIMARY KEY (map_pool_id, map_id)
Explain why

2020-03-15 18:57 UTC, norraxx commented on migrations/V82__map_pools.sql
> +    PRIMARY KEY (map_pool_id, map_id)
Reason is joining.
MySQL during query execution creates execution plan, it's the left handed tree (such data structure), that is made by query optimizer.
Query optimizer can swap tables as much as it want, unless `STRAIGHT JOIN` is in query.
And now imagine 3 tables:
`a`, (our `map_pool_maps`) and table `c` and then:
`a` join `map_pool_maps` on `map_pool_id` column and then table `c` on column `map_id`, but WHAT IF there is filter (where condition) on table `c`, like `c`.`id` = 1?
Then execution plan should be something like:
`c` join `map_pool_maps` on `map_id` and then join `a`.

And such execution plan WILL be created, BUT it will be ineffective.

And now the important question: `How MySQL uses coverage indexes?`
It uses them from left to right. First you will give columns for joins, then for filters, then for result.

So as you see, with the second case from `c` to `a` join, there will be no reason to:
1. open main table
2. do the full table scan
3. multiply results and do big temporary table in memory

Just open index, and use it for first and second join. With primary index it will work same (from `a` to `c`), way but you defined it explicit.

Did I describe it enough?

2020-03-17 07:33 UTC, Askaholic commented on migrations/V82__map_pools.sql
> +) COMMENT="A collection of maps, used by a matchmaker for map selection";
I wasn't planning on searching by them. They would be just for historical purposes.

2020-03-21 06:46 UTC, Askaholic commented on migrations/V82__map_pools.sql
> +    matchmaker_pool_id  INT REFERENCES matchmaker_pool (id),
Right now this is set up as a many-to-one relationship to matchmaker_pool. Do we instead want a many-to-many relationship? Is it conceivable that we would want to set up a single map pool that is used by multiple queues? For instance a casual and a tryhard version of the same queue.

2020-03-21 15:19 UTC, Geosearchef approved these changes
looks good to me

2020-03-21 15:19 UTC, Geosearchef commented on migrations/V82__map_pools.sql
> +    matchmaker_pool_id  INT REFERENCES matchmaker_pool (id),
I think a many-to-many relationship is a good idea. It will then apply the same rating range to both queues though.

2020-03-24 01:07 UTC, Askaholic commented on migrations/V82__map_pools.sql
> +    matchmaker_pool_id  INT REFERENCES matchmaker_pool (id),
We could also add the rating ranges into the many-to-many table. Not sure if we'd want that, but it probably doesn't hurt to have the flexibility right? It will possibly mean extra data in the database, but I don't think it will be a big deal since we probably wont ever have more than a handful of queues, and eve over long periods of time probably only hundreds of map pools.

2020-03-24 09:50 UTC, norraxx commented on migrations/V82__map_pools.sql
> +    max_rating          INT,
I don't see the logic behind that two columns  (min/max rating), but i think there will be some sort of computation with it, and i suggest to make add them to indexes, primary will have them automatically, but secondary might have them too.
Reason: every secondary index has pointer to primary index, and when we search from secondary index and asking for values that are not in secondary index primary index is opened and searched. For such small table - there is no reason to open primary index.

2020-03-24 18:35 UTC, Askaholic commented on migrations/V82__map_pools.sql
> +    max_rating          INT,
I don't think we need to add an index to these columns. We will never fetch a map pool based on rating. These tables are assumed to be changing very infrequently so we will just fetch them once per 10 minutes and cache the results in memory.

2020-03-28 10:27 UTC, axel1200 commented
@Brutus5000 merge or not merge?

2020-03-28 10:30 UTC, axel1200 commented
@Askaholic try to use the original repo and not a fork now we can not see if the CI runs through fro rxample

2020-03-28 16:18 UTC, axel1200 commented
@Brutus5000 I think you are the only one being allowed to merge on the db repo

2020-03-28 21:53 UTC, Brutus5000 requested changes

2020-03-28 21:53 UTC, Brutus5000 commented on migrations/V82__map_pools.sql
> +    map_id        INT NOT NULL REFERENCES map_version (id),
If it references a map version, it should also be called map_version_id

2020-03-28 21:53 UTC, Brutus5000 commented on migrations/V82__map_pools.sql
> +CREATE TABLE matchmaker_pool_map_pools
I do get the intention of the table, but the naming is unpleasant.
Going with existing namings we would have something like matchmaker_pool_assignments.

2020-03-28 22:02 UTC, Askaholic commented on migrations/V82__map_pools.sql
> +CREATE TABLE matchmaker_pool_map_pools
Hmm, I agree its not a nice name, the only problem with `matchmaker_pool_assignments` is that it doesn't capture the bidirectional relationship. Like `map_pool_maps` would become `map_pool_assignment` which doesn't make nearly as much sense.

2020-03-28 22:08 UTC, Brutus5000 commented on migrations/V82__map_pools.sql
> +CREATE TABLE matchmaker_pool_map_pools
Maybe matchmaker_subpools ?

2020-03-28 22:11 UTC, Askaholic commented on migrations/V82__map_pools.sql
> +CREATE TABLE matchmaker_pool_map_pools
Or `matchmaker_map_pools`. I could rename `matchmaker_pool` too since it isnt used yet. I'm not sure why it even has `pool` in the name

2020-04-05 15:11 UTC, Brutus5000 approved these changes

2020-04-05 15:11 UTC, merged