Add leaderboard entries for global and ladder_1v1.
FAForever/db pull request #217
Opened 2020-04-11 12:48 UTC by cleborys

Populate `leaderboard` with rating types for global and ladder 1v1, see #197.

Necessary for https://github.com/FAForever/server/pull/553 / https://github.com/FAForever/server/issues/534.
 
I hope I am using `name_key` and `description_key` as intended.

2020-04-11 13:19 UTC, norraxx commented on migrations/V84_add_leaderboard_entries.sql
> +INSERT INTO messages (key, language, region, value) VALUES
BTW: where do we use localization?

2020-04-11 13:19 UTC, norraxx commented
For me seems good

2020-04-11 19:11 UTC, Askaholic commented on migrations/V84_add_leaderboard_entries.sql
> +  (1, 'global', 'leaderboard.global.name', 'leaderboard.global.description'),
I'm not entirely sure how the i18n keys are supposed to work. I didn't even know there was a `messages` table, I assumed these keys would map to a file in the client somewhere. Maybe @Brutus5000 knows.

2020-04-11 21:39 UTC, Brutus5000 commented on migrations/V84_add_leaderboard_entries.sql
> +  (1, 'global', 'leaderboard.global.name', 'leaderboard.global.description'),
https://github.com/FAForever/db/blob/develop/migrations/V1__base.sql#L1053

But it's not that well maintained.

2020-04-11 21:40 UTC, Brutus5000 requested changes
The file needs a double underscore after the version number.

2020-04-15 15:13 UTC, Brutus5000 approved these changes

2020-04-15 15:13 UTC, merged