WIP: Add modifications for matchmaking
FAForever/db pull request #224
Opened 2020-05-13 21:01 UTC by Askaholic

I might split `team_size` into two columns `min_team_size` and `max_team_size` depending on how flexible we think queues need to be.

Adding a nullable reference to `matchmaker_queue.id` in the `game_stats` table should give us a cleaner way of distinguishing between custom/ladder games without the need for a fake featured_mod.  We could even go through and link up all previous ladder games (including old games that were played on the `faf` featured mod) to make it easier to query stats on ladder games.

# TODOs
- [ ] Set `matchmaker_queue_id` for all existing ladder games? Maybe make it a separate migration so we can ensure that we don't miss any during transition.

2020-05-16 13:20 UTC, norraxx commented on migrations/V89__matchmaker_enhancements.sql
> +  ADD COLUMN enabled BOOLEAN NOT NULL DEFAULT TRUE
Will be there any queries with filtering over this columns?

2020-05-18 03:28 UTC, Askaholic commented on migrations/V89__matchmaker_enhancements.sql
> +  ADD COLUMN enabled BOOLEAN NOT NULL DEFAULT TRUE
Yea I think so

2020-05-26 20:36 UTC, Brutus5000 requested changes

2020-05-26 20:36 UTC, Brutus5000 commented on migrations/V93__matchmaker_enhancements.sql
> +  ADD COLUMN matchmaker_queue_id INT UNSIGNED REFERENCES matchmaker_queue (id)
Wrong decleration of the foreign key constraint. See [manual](https://dev.mysql.com/doc/refman/5.6/en/create-table.html)
MySQL parses but ignores “inline REFERENCES specifications” (as defined in the SQL standard) where the references are defined as part of the column specification.
MySQL accepts REFERENCES clauses only when specified as part of a separate FOREIGN KEY specification.

2020-05-26 20:36 UTC, Brutus5000 commented on migrations/V93__matchmaker_enhancements.sql
> +  ADD COLUMN matchmaker_queue_id INT UNSIGNED REFERENCES matchmaker_queue (id)
`game_stats` is the largest table we have with > 20 million records, so we really need to think about changes carefully.
a) When is this populated? Only for ladder and TMM? So only a small portion of the games at all? Then maybe an additional m:n table should be used.
b) Do we really need an int? A smallint should be sufficient. (The same should happen in leaderboard_* tables by the way)

2020-05-27 00:04 UTC, norraxx commented on migrations/V93__matchmaker_enhancements.sql
> +  ADD COLUMN matchmaker_queue_id INT UNSIGNED REFERENCES matchmaker_queue (id)
:see_no_evil:

2020-06-02 00:59 UTC, Askaholic commented on migrations/V93__matchmaker_enhancements.sql
> +  ADD COLUMN matchmaker_queue_id INT UNSIGNED REFERENCES matchmaker_queue (id)
OK I think I'll do this in a follow up PR since I don't want to think about it right now :P

2020-06-02 01:03 UTC, Askaholic commented on migrations/V93__matchmaker_enhancements.sql
> +  ADD COLUMN matchmaker_queue_id INT UNSIGNED REFERENCES matchmaker_queue (id)
Wow I'm surprised I never heard about this in my databases course... We specifically used mysql for the entire relational db part of the course.

2020-06-02 06:32 UTC, Brutus5000 commented on migrations/V93__matchmaker_enhancements.sql
> +  ADD COLUMN matchmaker_queue_id INT UNSIGNED REFERENCES matchmaker_queue (id)
norraxx and I encountered this on accident just 1 day before your PR as I did not find the index in my db tool :slightly_smiling_face:

2020-06-02 13:56 UTC, Brutus5000 approved these changes

2020-06-02 13:56 UTC, merged