Populate leaderboard_rating_journal as migration 95
FAForever/db pull request #228
Opened 2020-06-06 23:23 UTC by cleborys

To fill `leaderboard_rating_journal` with entries from old games, we only need to determine the `leaderboard_id` column, currently either the one belonging to `global` or to `ladder_1v1`.

For newer games (since mid 2014?) that is easy to do by looking at the featured mod ("faf" or "ladder_1v1"), but for earlier games the ladder mod doesn't exist and we try to guess it instead.
Here "earlier" means `game_stats.id < 1996398" or `game_stats.startTime < "2014-03-22 12:59:25"`.
I am not sure how that choice made, but Askaholic should know.

On my laptop the query takes about 10 minutes, so I'm not sure how feasible it is as a migration, but maybe this gives you at least the chance to give me feedback on the SQL (much of which I had to acquire for this :sweat_smile: But now at least I know that terrible things happen if you don't include an `ON` in the join, outside of sqlalchemy.)

Questions
 1. Is `game_featuredMods.gamemod IN ("faf", "ladder_1v1")` too restrictive?
 1. There is only a couple of thousand games passing the WHERE clause with `game_stats.id < 1996398", is that expected?
 1.  Maybe the `ORDER BY` is superfluous? It would be nice if the order of `leaderboard_rating_journal.id` still reflects the historical timeline
 1. Should we include other re-computations like win ratio?

ToDo
 - [ ] Check that `game_stats.id = 1996398` is the first game with featured mod `ladder_1v1` or something reasonable like that
 - [ ] Do some sanity checks

2020-06-06 23:38 UTC, Askaholic requested changes
Pretty sure I came up with that date by looking at the earliest game to have the `ladder1v1` featured mod.

2020-06-06 23:38 UTC, Askaholic commented on migrations/V95__populate_leaderboard_rating_journal.sql
> +            WHEN game_featuredMods.gamemod = "ladder_1v1" THEN (SELECT id from leaderboard where leaderboard.technical_name = "ladder_1v1")
Game mod is `ladder1v1` with no underscore

2020-06-06 23:38 UTC, Askaholic commented on migrations/V95__populate_leaderboard_rating_journal.sql
> +      game_stats.validity = 0
How about using the enum name `'VALID'`?

2020-06-06 23:38 UTC, Askaholic commented on migrations/V95__populate_leaderboard_rating_journal.sql
> +      game_featuredMods.gamemod IN ("faf", "ladder_1v1")
ladder1v1

2020-06-06 23:38 UTC, Askaholic commented on migrations/V95__populate_leaderboard_rating_journal.sql
> +              game_stats.gameName LIKE "% Vs %"
Unless you collate to `utf8_bin` this will not do a case sensitive match. The main problem is there are games called stuff like `400+ vs AI` or `Aussies vs The World`, so doing a case sensitive match should cut down on false positives.

2020-06-07 09:31 UTC, cleborys commented on migrations/V95__populate_leaderboard_rating_journal.sql
> +      game_stats.validity = 0
I was trying to avoid the extra join, but I guess this one literally doesn't matter :)

2020-06-07 11:17 UTC, norraxx commented on migrations/V95__populate_leaderboard_rating_journal.sql
> +              ) = 2
There is no difference between 
```sql
AND
              (
                SELECT COUNT(*)
                FROM game_player_stats
                WHERE game_player_stats.gameId = game_stats.id
              ) = 2
```
and
```sql
              AND
              (
                SELECT COUNT(*)
                FROM game_player_stats
                WHERE game_player_stats.gameId = game_stats.id
                AND game_player_stats.AI = FALSE
                AND game_player_stats.color IN (1, 2)
                AND game_player_stats.score IN (-1, 0, 1)
              ) = 2
```

Second condition is much more restrictive, so i'd remove first one.

2020-06-07 11:23 UTC, norraxx commented on migrations/V95__populate_leaderboard_rating_journal.sql
> +              game_stats.gameName LIKE _utf8 "% Vs %" COLLATE utf8_bin
Where dif you find `LIKE _utf8`, or what it does?

2020-06-07 11:38 UTC, norraxx commented on migrations/V95__populate_leaderboard_rating_journal.sql
> +            ELSE (SELECT id from leaderboard where leaderboard.technical_name = "global")
Don't do this selects, use our known value:

```
"ladder_1v1" - 2
"global" - 1
```
Less subdependant queries you do, faster it will

2020-06-07 11:38 UTC, norraxx commented on migrations/V95__populate_leaderboard_rating_journal.sql
> +            ELSE (SELECT id from leaderboard where leaderboard.technical_name = "global")
same here, use constants instead of selects

2020-06-07 11:45 UTC, norraxx commented
```sql
EXPLAIN
INSERT INTO leaderboard_rating_journal (
  game_player_stats_id, 
  leaderboard_id, 
  rating_mean_before, 
  rating_deviation_before, 
  rating_mean_after, 
  rating_deviation_after
)
  SELECT
      game_player_stats.id,
      IF (
        game_stats.id < 1996398,
        IF (
          game_player_stats.score IN (-1, 0, 1) 
          AND
          game_stats.gameName LIKE _utf8 "% Vs %" COLLATE utf8_bin
          AND
          (
            SELECT COUNT(*)
            FROM game_player_stats
            WHERE game_player_stats.gameId = game_stats.id
            AND game_player_stats.AI = FALSE
            AND game_player_stats.color IN (1, 2)
            AND game_player_stats.score IN (-1, 0, 1)
          ) = 2,
          2,
          1
        ),
        IF (game_featuredMods.gamemod = "ladder1v1", 2, 1)
      ) AS leaderboard_id,
      game_player_stats.mean,
      game_player_stats.deviation,
      game_player_stats.after_mean,
      game_player_stats.after_deviation
    FROM
      game_stats
      JOIN
        game_player_stats ON (game_player_stats.gameId = game_stats.id)
      JOIN
        game_featuredMods ON (game_stats.gameMod = game_featuredMods.id)
      JOIN
        game_validity ON (game_stats.validity = game_validity.id)
    WHERE
      game_player_stats.after_mean IS NOT NULL
      AND
      game_player_stats.after_deviation IS NOT NULL
      AND
      game_validity.message = "Valid"
      AND
      game_featuredMods.gamemod IN ("faf", "ladder1v1")
    ORDER BY game_player_stats.id;
```

2020-06-07 11:45 UTC, norraxx commented on migrations/V95__populate_leaderboard_rating_journal.sql
> +      CASE
Imho, instead of big `CASE ... WHEN ... THEN ... END` you can use `IF` function, it will look like `SELECT IF(condition, value_if_true, value_if_false)`

Better readibility

2020-06-07 21:11 UTC, cleborys commented on migrations/V95__populate_leaderboard_rating_journal.sql
> +              ) = 2
Well, the idea is that you should have two players in the game and *both* players satisfy the strict requirements. Otherwise you could get a four player game where only two players satisfy the strict checks, so that you pass nonetheless.
You could also think of this as `number_of_players_that_look_as_if_this_is_ladder == number_of_players == 2`

This is all stolen from Askaholic's query in https://github.com/FAForever/server/pull/601, by the way.

2020-06-07 21:19 UTC, cleborys commented on migrations/V95__populate_leaderboard_rating_journal.sql
> +              game_stats.gameName LIKE _utf8 "% Vs %" COLLATE utf8_bin
I was of the impression that to do the `COLLATE` I would need to enter a utf8 string literal and that this is the way to do it. That doesn't seem true so I think it should be removed :)

2020-06-07 21:23 UTC, cleborys commented on migrations/V95__populate_leaderboard_rating_journal.sql
> +            ELSE (SELECT id from leaderboard where leaderboard.technical_name = "global")
That is true. There is no easy way to save these in local variables/constants and then use these, right? Because I would prefer not to hardcode constants and rather have a
```
@ladder_leaderboard_id = (SELECT id from leaderboard where leaderboard.technical_name = "ladder_1v1")

// ...

CASE ...stuff... THEN @ladder_leaderboard_id
```

But if I'm not mistaken MySQL only allows that if I wrap it in a procedure?

2020-06-07 21:24 UTC, cleborys commented on migrations/V95__populate_leaderboard_rating_journal.sql
> +      CASE
Ah that's nice (and I didn't know about it) :+1:

2020-06-07 21:52 UTC, cleborys commented on migrations/V95__populate_leaderboard_rating_journal.sql
> +              game_stats.gameName LIKE _utf8 "% Vs %" COLLATE utf8_bin
On further inspection it seems necessary since otherwise the charset is `latin1`?
https://dev.mysql.com/doc/refman/5.7/en/charset-introducer.html

(`_utf8` is the MySQL v5.7 variant instead of `_utf8mb4` for MySQL v8.0)

2020-06-07 22:32 UTC, norraxx commented on migrations/V95__populate_leaderboard_rating_journal.sql
> +            ELSE (SELECT id from leaderboard where leaderboard.technical_name = "global")
You know this values already, they are constants. It's one and two :-)

2020-06-07 22:38 UTC, norraxx commented on migrations/V95__populate_leaderboard_rating_journal.sql
> +    END AS after_deviation
Oh my holy zombie jesus :-)

2020-06-07 22:40 UTC, norraxx commented on migrations/V95__populate_leaderboard_rating_journal.sql
> +              ) = 2
IF they satisfy second condition, they'll also satisfy the first one.

2020-06-07 22:50 UTC, norraxx commented on migrations/V95__populate_leaderboard_rating_journal.sql
> +              game_stats.gameName LIKE _utf8 "% Vs %" COLLATE utf8_bin
`The introducer is just a signal` - so i don't get why would you need it?
Do we want to have case sensitive like? If yes, maybe we should use `utf8mb4_bin`, because we have `utf8mb4_unicode_ci` in `gameName`?

Also `utf8` vs `utf8mb4` is not the same, they're not compatibile, there is a difference and support between mysql versions.

2020-06-07 22:53 UTC, norraxx commented on migrations/V95__populate_leaderboard_rating_journal.sql
> +      (SELECT id from leaderboard where leaderboard.technical_name = "global")
If you want to have QUERY in select part of the QUERY, how about to use `SELECT 1`? :see_no_evil:

2020-06-07 22:57 UTC, norraxx commented on migrations/V95__populate_leaderboard_rating_journal.sql
> +      ELSE game_player_stats.deviation
First of all, this is typical case for using `coalesce`:

`COALESCE(game_player_stats.after_deviation, inner_game_player_stats.deviation, game_player_stats.deviation)`

2020-06-07 23:03 UTC, norraxx commented on migrations/V95__populate_leaderboard_rating_journal.sql
> +        )
I don't undrstand, why would you need that double query? Like getting next deviation that is bigger than this current result, for current player and mod. O_o. What are you trying to solve?

And If you need it so badly, why would you do it as dependant query, why not to join it bellow as 2x left join (i'll write)

2020-06-07 23:06 UTC, norraxx commented on migrations/V95__populate_leaderboard_rating_journal.sql
> +      game_validity ON (game_stats.validity = game_validity.id)
continue from above
```sql
LEFT JOIN game_player_stats inner_game_player_stats 
ON (
	inner_game_player_stats.playerId = game_player_stats.playerId
)
LEFT JOIN game_stats inner_game_stats 
ON (
		inner_game_player_stats.gameId = inner_game_stats.id
	AND inner_game_stats.id > game_stats.id
	AND inner_game_stats.gameMod = game_stats.gameMod
)

```

2020-06-07 23:07 UTC, norraxx commented
When i see it, maybe we should process this results like in bulks with python script? It won't be blocking operation, in small transactions, just go one by one... Commit like every 1000 rows...

2020-06-08 05:51 UTC, Askaholic commented on migrations/V95__populate_leaderboard_rating_journal.sql
> +              ) = 2
Not true. Consider a game with 2 human players which satisfy all conditions and one AI player. The second query will return a count of 2 but the first query will return a count of 3.

2020-06-08 05:53 UTC, Askaholic commented on migrations/V95__populate_leaderboard_rating_journal.sql
> +              game_stats.gameName LIKE _utf8 "% Vs %" COLLATE utf8_bin
Isn't ASCII the same in latin1 and utf8? Since the literal is just ASCII I don't think it matters.

2020-06-08 05:54 UTC, Askaholic commented on migrations/V95__populate_leaderboard_rating_journal.sql
> +            ELSE (SELECT id from leaderboard where leaderboard.technical_name = "global")
Strings are better. They are more readable and the table is tiny. There will be no performance cost.

2020-06-08 05:56 UTC, Askaholic commented on migrations/V95__populate_leaderboard_rating_journal.sql
> +        )
See discussion on zulip in `#tmm-discussions`

2020-06-08 08:54 UTC, cleborys commented on migrations/V95__populate_leaderboard_rating_journal.sql
> +              game_stats.gameName LIKE _utf8 "% Vs %" COLLATE utf8_bin
So what do you suggest? Simply removing `_utf8` makes the query fail with `COLLATION 'utf8_bin' is not valid for CHARACTER SET 'latin1'`, see https://travis-ci.org/github/FAForever/db/builds/695789080.

And I thought `utf8mb4` is not yet supported in MySQL v3.7 which the docker image is using?

2020-06-08 08:56 UTC, cleborys commented on migrations/V95__populate_leaderboard_rating_journal.sql
> +        )
One sentence summary: There are two years worth of of `game_player_stats` rows for ladder games, which have nulled out the `after_mean`, so we try to look it up from the next game the player played instead.

2020-06-08 12:09 UTC, norraxx commented on migrations/V95__populate_leaderboard_rating_journal.sql
> +            ELSE (SELECT id from leaderboard where leaderboard.technical_name = "global")
There is performance cost. Each dependant subquery is bad.
We should get data in join phase.

2020-06-08 19:19 UTC, Brutus5000 commented
From the supcomhub migration stuff I have this leftover repair migration:

```
UPDATE faf.game_stats SET gamemod = 6
WHERE gamemod = 0 AND
        startTime < '2014-03-22 12:59:25' AND
        gameName LIKE '% Vs %' AND
        (
            SELECT count(*) FROM faf.game_player_stats
            WHERE gameId = faf.game_stats.id
        ) = 2
  AND
        (
            SELECT count(*) FROM faf.game_player_stats
            WHERE gameId = faf.game_stats.id AND
                    AI = false AND
                    color IN (1, 2) AND
                    score in (-1, 0, 1)
        ) = 2;
```

Running this first would make things a lot easier and the other queries less complex.

2020-06-08 19:45 UTC, cleborys commented
Seeing that there are two years of games which don't have the `after_mean` filled in, as well as a couple of rating hiccups, where games were rated out of order and overwrote previous rating changes, after talking to Askaholic I'd suggest that instead of trying to copy data over we re-rate the entire game history.
Once we have an independent rating service that should be a lot easier by simply "replaying" the appropriate messages for all valid past games.

2020-06-08 20:44 UTC, Askaholic commented
Oh yea we should definitely run that sort of repair migration first. We probably should have done that when I tried to fix the win ratio before, but oh well.

2020-06-09 16:42 UTC, cleborys commented
Closed in favour of re-rating the entire history in a batch job, necessary cleanup moved to #231.

2020-06-09 16:42 UTC, closed without merging

2020-06-09 16:45 UTC, cleborys commented on migrations/V95__populate_leaderboard_rating_journal.sql
> +      ELSE game_player_stats.deviation
Oh that's very nice.