Old game cleanup
FAForever/db pull request #231
Opened 2020-06-09 16:40 UTC by cleborys

The first query sets the featured mod of old ladder games where the `ladder1v1` mod didn't yet exist, but where we can be reasonably confident they were ladder. (Discussed in many places, most recently in https://github.com/FAForever/db/pull/228.)

The second query finds games where the associated `game_player_stats` rows don't have the `playerId` filled in correctly with the id of the same player repeated every row.
Here is an example: 
```
mysql> select * from game_player_stats where gameId = 4393013;                                            
+---------+---------+----------+----+---------+-------+------+-------+---------+-----------+------------+-----------------+-------+---------------------+---------+
| id      | gameId  | playerId | AI | faction | color | team | place | mean    | deviation | after_mean | after_deviation | score | scoreTime           | result  |
+---------+---------+----------+----+---------+-------+------+-------+---------+-----------+------------+-----------------+-------+---------------------+---------+
| 8183192 | 4393013 |   150494 |  0 |       1 |     3 |    3 |     7 | 676.332 |   207.979 |       NULL |            NULL |    -1 | 2016-02-03 15:47:13 | UNKNOWN |
| 8183193 | 4393013 |   150494 |  0 |       4 |     5 |    2 |     1 | 1376.66 |   195.131 |       NULL |            NULL |    -1 | 2016-02-03 15:47:13 | UNKNOWN |
+---------+---------+----------+----+---------+-------+------+-------+---------+-----------+------------+-----------------+-------+---------------------+---------+

 mysql> select * from game_stats where id = 4393013;
+---------+---------------------+---------------------+--------------+----------+---------+--------+-------+------------------------+----------+
| id      | startTime           | endTime             | replay_ticks | gameType | gameMod | host   | mapId | gameName               | validity |
+---------+---------------------+---------------------+--------------+----------+---------+--------+-------+------------------------+----------+
| 4393013 | 2016-02-03 15:47:13 | 2016-02-03 15:47:18 |         NULL | 3        |       0 | 133570 |  NULL |   [PLAYER NAME]'s game |        2 |
+---------+---------------------+---------------------+--------------+----------+---------+--------+-------+------------------------+----------+
```
This seems to have been a short-lived bug for a few weeks around February 2016, around the time of the introduction of the `ladder1v1 mod`.
Over all, about 20k valid games are affected and to prevent these from messing with re-calculating rating history I would suggest we set their validity to `"Unranked for another reason"`.
To speed up the query I restricted it to the range of (valid) affected games:
```
mysql> select min(game_stats.id) AS min_game_id, max(game_stats.id) AS max_game_id , count(*) AS game_count FROM game_stats LEFT JOIN game_player_stats ON (game_stats.id = game_player_stats.gameId) WHERE game_stats.validity = 0 AND (SELECT count(*) from game_player_stats where game_player_stats.gameId = game_stats.id) != (SELECT count(DISTINCT playerId) from game_player_stats where game_player_stats.gameId = game_stats.id);
+-------------+-------------+------------+
| min_game_id | max_game_id | game_count |
+-------------+-------------+------------+
|     4393128 |     4424726 |      18219 |
+-------------+-------------+------------+
1 row in set (3 min 32.63 sec)
```
(The example game above is notably outside of that range, but the validity is already set to invalid (not assassination mode).)

2020-06-09 16:43 UTC, cleborys commented on migrations/V95__laddermod_cleanup.sql
> +  gameName LIKE _utf8 "% Vs %" COLLATE utf8_bin
I still don't understand how to do case sensitive matching without the `_utf8`, feel free to let me know what I'm missing :kissing_heart:

2020-06-09 19:29 UTC, Brutus5000 commented on migrations/V95__laddermod_cleanup.sql
> +  gameName LIKE _utf8 "% Vs %" COLLATE utf8_bin
The collation of the column is case insensitive, so you shouldn't need to?

2020-06-09 19:30 UTC, Brutus5000 commented on migrations/V95__laddermod_cleanup.sql
> +  faf.game_stats.id < 4424727
There is this magic operator called between.

2020-06-09 19:32 UTC, Brutus5000 commented on migrations/V95__laddermod_cleanup.sql
> +AND
From my experience these kind of subselects run forever. Can you put the the subselect results into a temporary table and join them=

2020-06-09 21:52 UTC, cleborys commented on migrations/V95__laddermod_cleanup.sql
> +  faf.game_stats.id < 4424727
magic indeed.

2020-06-09 22:21 UTC, cleborys commented on migrations/V95__laddermod_cleanup.sql
> +AND
I'm learning something new with every query I write! Let's see if I understood you correctly :P

2020-06-09 22:27 UTC, norraxx requested changes

2020-06-09 22:27 UTC, norraxx commented on migrations/V95__laddermod_cleanup.sql
> +  gameName LIKE _utf8 "% Vs %" COLLATE utf8_bin
He need to have a exact match, to know that's game name is not made by user. (it's not 100% sure)

On test i see:
```sql
`gameName` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL
```
So i would use  `utf8mb4_bin`, not `utf8_bin`, reason is number of bytes per character, it can be different.
And i still don't get this `_utf8`, so you can remove it with `utf8mb4_bin`

2020-06-09 22:27 UTC, norraxx commented on migrations/V95__laddermod_cleanup.sql
> +;
Please, remove all database prefixes (`faf.`). This query won't work on test.

2020-06-09 22:31 UTC, norraxx commented on migrations/V95__laddermod_cleanup.sql
> +;
`DROP TEMPORARY TABLE faf.game_player_count;` :-)

2020-06-09 22:34 UTC, norraxx commented on migrations/V95__laddermod_cleanup.sql
> +  gps_row_count != distinct_player_count
it's good to have from which table did you get this column. Like mysql will resolve it, but my eyes not :-D

2020-06-09 22:34 UTC, norraxx commented on migrations/V95__laddermod_cleanup.sql
> +      faf.game_stats.id
Hmm, i think, you could filter results by clause `HAVING`, which is applied after `group by`, so you'll have your table smaller.

`HAVING gps_row_count != distinct_player_count`

2020-06-09 22:36 UTC, norraxx commented on migrations/V95__laddermod_cleanup.sql
> +      faf.game_stats.id
And ofc you won't need that condition in query bellow

2020-06-09 22:40 UTC, norraxx commented
@cleborys @Askaholic Guys, you'll have conflicts with migration in names #230 #231. Also `V96__` is used by #227.

2020-06-10 11:02 UTC, cleborys commented on migrations/V95__laddermod_cleanup.sql
> +  gameName LIKE _utf8 "% Vs %" COLLATE utf8_bin
Here's an example where case sensitivity matters
```
mysql> select game_stats.id, game_stats.gameName from game_stats where gameName LIKE "% Vs %" and gameName not LIKE _utf8 "% Vs %" COLLATE utf8_bin;
+---------+------------+
| id      | gameName   |
+---------+------------+
| // ...               |
| 6169271 | ZLO 4 vs 1 |
| // ...               |
+---------+------------+
```

2020-06-10 11:06 UTC, cleborys commented on migrations/V95__laddermod_cleanup.sql
> +  gameName LIKE _utf8 "% Vs %" COLLATE utf8_bin
What I didn't understand before is that you don't need to make the literal string `_utf8` if you collate the column instead of the string :+1:

2020-06-10 11:14 UTC, cleborys commented
I renamed it to `V97__` so the other two PRs can use `V95__` and `V96__`.

2020-06-10 21:19 UTC, Askaholic commented
Tbh renaming files is trivial. My approach is to always use the next available number and rebase my PR if something else is merged. Yea it can delay by 1 day or something but that’s not a big deal here at FAF

2020-06-24 22:04 UTC, norraxx reviewed
I suppose your code will work, unfortunately i don't have a data on local machine. I'm offering to sit some evening together and make some queries together.

2020-06-24 22:04 UTC, norraxx commented on migrations/V97__laddermod_cleanup.sql
> +  gamemod = 6
`gameMod`

2020-06-24 22:04 UTC, norraxx commented on migrations/V97__laddermod_cleanup.sql
> +    WHERE gameId = game_stats.id
[proposition for better code]

I would preffer to read code like

```
select part
tables part + join filters
conditions part
order part
having part.
```
It's easier to read when it's on different lines.

\+ keywords like function names, etc.. could be ca(ra)melized. :-)
[/proposition for better code]

2020-06-24 22:04 UTC, norraxx commented on migrations/V97__laddermod_cleanup.sql
> +  ) = 2
I still don't think, that you need that first condition. Sorry, but your second query to the table is more restrictive. And mostly it will do whole job that you'll need. Query above will be still filtered by query bellow.

Let's have a talk some time about it?

2020-06-24 22:16 UTC, Askaholic commented on migrations/V97__laddermod_cleanup.sql
> +  ) = 2
You need both conditions:

Consider a game with 2 human players which satisfy all conditions and one AI player. The second query will return a count of 2 but the first query will return a count of 3.

2020-09-08 19:40 UTC, Brutus5000 commented
@cleborys Is this work in progress or do you consider this finished? In the latter case, please move to the version 103

2020-09-14 10:52 UTC, cleborys commented
I have added noraxx' formatting suggestions and rebased, I believe this is ready.

2020-09-14 13:41 UTC, Brutus5000 approved these changes

2020-09-14 13:42 UTC, merged