Ranks for leaderboard
FAForever/db pull request #234
Opened 2020-06-23 22:15 UTC by axel1200

Fixes #233

2020-06-23 22:20 UTC, bukajsytlos requested changes

2020-06-23 22:20 UTC, bukajsytlos commented on migrations/V97__rating_materialized_view.sql
> +        DELETE FROM ladder1v1_rating_rank_view;
global

2020-06-23 22:21 UTC, bukajsytlos requested changes
Original "view" ignored banned players

2020-06-23 23:33 UTC, norraxx requested changes

2020-06-23 23:33 UTC, norraxx commented on migrations/V97__rating_materialized_view.sql
> +    id        mediumint unsigned             not null,#
`#` ?

2020-06-23 23:33 UTC, norraxx commented on migrations/V97__rating_materialized_view.sql
> +               @r := (@r + 1),
What's the difference between some auto incremented column and this magic that replaces function from mysql 8 `row_number()`. You flush table always, so add there some auto incremented column, set it to 0 and do anything you want without session values, that can be common for both events.

2020-06-23 23:34 UTC, norraxx commented
> Tell me how to improve

Use big letters, it's nice to read after that

2020-06-23 23:35 UTC, norraxx commented
> I copied from stack overflow so I guess I should use a local variable

See auto incremented column solution below.

2020-06-23 23:37 UTC, norraxx commented
> I copied from stack overflow so I guess I should use a local variable

Yes, i understand and for session and simple querying to database it will work well. Unfortunately i don't know how session variables behave during events and if two events are running same time, and have same named variable, how they will behave.

2020-06-24 08:41 UTC, axel1200 commented on migrations/V97__rating_materialized_view.sql
> +               @r := (@r + 1),
I think we dont have mysql 8

2020-06-24 08:43 UTC, axel1200 commented on migrations/V97__rating_materialized_view.sql
> +               @r := (@r + 1),
There is also a RANK() function but well we are not mysql 8 it seems

2020-06-24 08:44 UTC, axel1200 commented on migrations/V97__rating_materialized_view.sql
> +               @r := (@r + 1),
Yeah nice if we could do it together one day

2020-06-24 11:13 UTC, norraxx commented on migrations/V97__rating_materialized_view.sql
> +               @r := (@r + 1),
Sure! Let's do it today or tomorrow evening.

2020-06-24 11:47 UTC, axel1200 commented on migrations/V97__rating_materialized_view.sql
> +               @r := (@r + 1),
today sounds good

2020-06-24 19:19 UTC, axel1200 commented on migrations/V97__rating_materialized_view.sql
> +        DELETE FROM ladder1v1_rating_rank_view;
yes

2020-06-24 19:19 UTC, axel1200 commented on migrations/V97__rating_materialized_view.sql
> +    id        mediumint unsigned             not null,#
yes

2020-06-24 19:20 UTC, axel1200 commented on migrations/V97__rating_materialized_view.sql
> +               @r := (@r + 1),
Well I did research and i can not use these local variables. They don't offer setting them inside a query. So I need to stick with session variables. But I called them differently so it avoids any collisions.

2020-06-24 21:05 UTC, norraxx reviewed
I'm sexy and I know it.

2020-06-24 21:27 UTC, norraxx approved these changes

2020-06-24 21:29 UTC, axel1200 commented
https://github.com/FAForever/faf-java-api/pull/405

2020-06-28 20:19 UTC, Brutus5000 requested changes

2020-06-28 20:19 UTC, Brutus5000 commented on migrations/V97__rating_materialized_view.sql
> +           0,
Global rating doesn't have won games. Putting in 0 value isn't making it better.

2020-06-28 21:55 UTC, norraxx commented on migrations/V97__rating_materialized_view.sql
> +           0,
Do you propose null value? Like it what got into our heads with alex.

2020-06-29 04:30 UTC, Brutus5000 commented on migrations/V97__rating_materialized_view.sql
> +           0,
I propose to drop the column so nobody queries wrong stuff in the API.

2020-06-29 05:09 UTC, norraxx commented on migrations/V97__rating_materialized_view.sql
> +           0,
@axel1200 ?

2020-06-29 09:02 UTC, 1-alex98 commented on migrations/V97__rating_materialized_view.sql
> +           0,
ok, just thought I leave it there because should be there. Or maybe put null.

2020-06-29 09:04 UTC, 1-alex98 commented
Removed it

2020-07-03 06:58 UTC, norraxx requested changes

2020-07-03 06:58 UTC, norraxx commented on migrations/V97__rating_materialized_view.sql
> +                 INNER JOIN game_stats gs on gps.gameId = gs.id
formatting :-)

2020-07-03 06:58 UTC, norraxx commented on migrations/V97__rating_materialized_view.sql
> +      AND  is_active = 1
:thinking: You don't use `active_players` in this event.

Also I don't understand this condition.
`((ban.expires_at is null or ban.expires_at > NOW()) AND ban.revoke_time IS NULL)`
Infinite ban expire, or ban is in future and ban is not revoked.
You want to join and have only banned players? O_o

Imho copy-paste kung-fu :see_no_evil:

2020-07-03 06:58 UTC, norraxx commented on migrations/V97__rating_materialized_view.sql
> +    CREATE TEMPORARY TABLE active_players ENGINE=MEMORY AS
Also when i see this, I'm thinking about to have an materialized view for active players, refreshed once per day.
I've seen this query with such conditions already on some places.

2020-07-03 06:58 UTC, norraxx commented on migrations/V97__rating_materialized_view.sql
> +                 INNER JOIN game_stats gs on gps.gameId = gs.id
formatting

2020-07-03 06:58 UTC, norraxx commented on migrations/V97__rating_materialized_view.sql
> +    CREATE TEMPORARY TABLE active_players ENGINE=MEMORY AS
Also you're making table 2 times with same name `active_players` at two places, but data are differrent. I'd name them different, to avoid undefined behavior between two events run.

2020-07-03 20:54 UTC, Brutus5000 commented on migrations/V97__rating_materialized_view.sql
> +      AND  is_active = 1
Yes, stupid. Fixed now.

2020-07-03 20:54 UTC, Brutus5000 commented on migrations/V97__rating_materialized_view.sql
> +    CREATE TEMPORARY TABLE active_players ENGINE=MEMORY AS
I only ever saw querying active players for the leaderboard.

2020-07-03 20:54 UTC, Brutus5000 commented on migrations/V97__rating_materialized_view.sql
> +    CREATE TEMPORARY TABLE active_players ENGINE=MEMORY AS
I renamed the 2 temp tables now to avoid collisions as suggested.

2020-07-03 21:22 UTC, norraxx approved these changes

2020-07-05 17:46 UTC, axel1200 commented
Approve as well

2020-07-05 19:04 UTC, Brutus5000 approved these changes

2020-07-05 19:04 UTC, merged