Only consider global bans on filtering active players
FAForever/db pull request #245
Opened 2020-08-17 21:11 UTC by Brutus5000

fixes #244

2020-08-18 11:12 UTC, norraxx requested changes

2020-08-18 11:12 UTC, norraxx commented on migrations/V101__consider_ban_in_rating_tables.sql
> +                         INNER JOIN game_stats gs on gps.gameId = gs.id
I would format it.

2020-08-18 11:12 UTC, norraxx commented on migrations/V101__consider_ban_in_rating_tables.sql
> +                         INNER JOIN game_stats gs on gps.gameId = gs.id
-//-

2020-08-18 11:12 UTC, norraxx commented on migrations/V101__consider_ban_in_rating_tables.sql
> +        TRUNCATE global_rating_rank_view;
:thinking: 

`TRUNCATE <table>` is DDL, not DML. It will not be affected by transaction and I don't know if there is some deterministic behavior. It will cause implicit `COMMIT`. And rest of the code won't run in transaction.

`DELETE FROM global_rating_rank_view WHERE 1=1` ?

\+ Same for truncate above

2020-08-18 11:12 UTC, norraxx commented on migrations/V101__consider_ban_in_rating_tables.sql
> +            )
Please format it :-)

2020-08-18 11:12 UTC, norraxx commented on migrations/V101__consider_ban_in_rating_tables.sql
> +            )
please, format it

2020-08-19 19:49 UTC, Brutus5000 commented on migrations/V101__consider_ban_in_rating_tables.sql
> +            )
IntelliJ does weird stuff on copy&paste

2020-08-19 19:52 UTC, Brutus5000 commented on migrations/V101__consider_ban_in_rating_tables.sql
> +        TRUNCATE global_rating_rank_view;
ok

2020-08-19 20:01 UTC, merged