Fix rating sign
FAForever/db pull request #250
Opened 2020-09-24 03:33 UTC by Askaholic

For some reason the `mean` field on `game_player_stats` is set to unsigned, even though negative mean is OK. (Even `after_mean` is signed...). Really we want to make sure that DEVIATION is unsigned. Technically speaking I think deviation must always be strictly positive, deviation of 0 will cause issues, but I'm not sure it's possible or necessary to enforce that in MySQL.

The `ladder1v1_rating` and `global_rating` tables both allow negative deviation, and so do their corresponding rank views, but since those tables are more or less deprecated anyways I just left them.

2020-09-24 08:43 UTC, norraxx requested changes

2020-09-24 08:43 UTC, norraxx commented on migrations/V105__fix_rating_signedness.sql
> +  MODIFY after_deviation FLOAT UNSIGNED;
1. What FLOAT units are good for? I'm just curious why it's like that.
2. Also you're facing an error like: `Out of range value for column deviation`. I'd expect some sql that fixes the data before alter.

2020-09-24 20:03 UTC, Askaholic commented on migrations/V105__fix_rating_signedness.sql
> +  MODIFY after_deviation FLOAT UNSIGNED;
I don't think any of the deviations are negative, it's just a precaution. 

This is the error that we're getting in the server:
```
Traceback (most recent call last):
  File "/code/server/games/game.py", line 720, in update_game_player_stats
    await conn.execute(game_player_stats.insert().values(query_args))
  File "/code/src/aiomysql/aiomysql/sa/connection.py", line 173, in _execute
    await cursor.execute(str(compiled), post_processed_params)
  File "/code/src/aiomysql/aiomysql/cursors.py", line 239, in execute
    await self._query(query)
  File "/code/src/aiomysql/aiomysql/cursors.py", line 457, in _query
    await conn.query(q)
  File "/code/src/aiomysql/aiomysql/connection.py", line 428, in query
    await self._read_query_result(unbuffered=unbuffered)
  File "/code/src/aiomysql/aiomysql/connection.py", line 622, in _read_query_result
    await result.read()
  File "/code/src/aiomysql/aiomysql/connection.py", line 1105, in read
    first_packet = await self.connection._read_packet()
  File "/code/src/aiomysql/aiomysql/connection.py", line 593, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.DataError: (1264, "Out of range value for column 'mean' at row 3")
```

2020-10-01 19:03 UTC, Brutus5000 approved these changes

2020-10-01 19:06 UTC, Brutus5000 commented on migrations/V105__fix_rating_signedness.sql
> +  MODIFY after_deviation FLOAT UNSIGNED;
I verified in the database tables, there are no current/before/after deviations < 0

2020-10-01 19:07 UTC, merged