Add migration for weight and other map params
FAForever/db pull request #259
Opened 2021-03-03 02:21 UTC by Sheikah45

This is an initial pr for changing the database for changing the map_pool_map_version table to support other map params and map weights. It was generated by my mysql to make the change however there are issues with the foreign key and primary key. Currently there is no primary key as map_version_id can now be null and other_params can be null as well.

2021-03-03 02:22 UTC, Sheikah45 commented
This is tied to https://github.com/FAForever/server/pull/732#issue-581528027

2021-03-03 08:59 UTC, Brutus5000 requested changes

2021-03-03 08:59 UTC, Brutus5000 commented on migrations/V108__add_weight_and_other_params_to_map_pool_map_version.sql
> +    CHANGE COLUMN `map_version_id` `map_version_id` MEDIUMINT(8) UNSIGNED NULL ,
Add a comment what it means when it's null

2021-03-03 08:59 UTC, Brutus5000 commented on migrations/V108__add_weight_and_other_params_to_map_pool_map_version.sql
> +    ADD COLUMN `other_map_params` TEXT NULL AFTER `weight`,
I'm not happy with the name. Either call it map_generator_params or map_params, but remove the `other`. Also add a comment whats inside here such as: "A JSON containing parameters for the map generator"

2021-03-03 08:59 UTC, Brutus5000 commented on migrations/V108__add_weight_and_other_params_to_map_pool_map_version.sql
> +    DROP PRIMARY KEY;
We should add a new primary key with an auto incremented id

2021-03-04 09:32 UTC, Sheikah45 commented
Added the comments properly now

2021-03-12 11:24 UTC, Sheikah45 commented
moved to #262

2021-03-12 11:24 UTC, closed without merging