Add map_play_count trigger to record map plays
FAForever/db pull request #272
Opened 2021-04-06 13:01 UTC by Sheikah45

Fixes #270

2021-04-06 20:08 UTC, Brutus5000 commented
Table_map_features should be removed (It's not used by any service) and the column should go into map_version.
Also all values should be recomputed once to be correct

2021-04-06 20:33 UTC, Sheikah45 commented
Just so I am clear should that recomputation be a part of this migration

2021-04-06 23:37 UTC, Sheikah45 commented
Hmm actually the api does use table_map_features

2021-04-17 11:34 UTC, Sheikah45 commented
Reviews please?

2021-04-19 21:33 UTC, Brutus5000 requested changes

2021-04-19 21:33 UTC, Brutus5000 commented on migrations/V116__map_play_count_trigger.sql
> +WHERE table_map_features.map_id = map_plays.mapId;
Make it a view instead for compatibility while deprecating it (with a comment)

2021-04-19 21:33 UTC, Brutus5000 commented on migrations/V116__map_play_count_trigger.sql
> +WHERE map.id = map_plays.map_id;
These subselects are super costly from my experience. Better go for a join-based solution.

2021-04-19 22:05 UTC, Sheikah45 commented on migrations/V116__map_play_count_trigger.sql
> +WHERE map.id = map_plays.map_id;
Will do

2021-04-19 23:27 UTC, Sheikah45 commented on migrations/V116__map_play_count_trigger.sql
> +WHERE table_map_features.map_id = map_plays.mapId;
Would making it a view mean this query is run everytime someone wants to see the play count using the depreciated view which all clients currently do for any map in the vault? Would this be inefficient or am I missing something?

2021-04-20 12:03 UTC, Sheikah45 commented on migrations/V116__map_play_count_trigger.sql
> +WHERE table_map_features.map_id = map_plays.mapId;
Done although it looks like views can't have comments

2021-04-25 09:55 UTC, Sheikah45 commented
Was there anything else we wanted to change here?

2021-04-27 22:58 UTC, Brutus5000 approved these changes

2021-05-09 13:14 UTC, Brutus5000 approved these changes

2021-05-09 13:15 UTC, merged