Add recommended tables
FAForever/db pull request #278
Opened 2021-05-23 22:28 UTC by Sheikah45

2021-05-24 22:07 UTC, Brutus5000 requested changes

2021-05-24 22:07 UTC, Brutus5000 commented on migrations/v117__recommended_maps_and_mods.sql
> +    ADD COLUMN `recommended` boolean NOT NULL DEFAULT false COMMENT 'Boolean to indicate if a map is a high quality FAF Mod' AFTER `reviews`;
in the comment map = mod :D

2021-05-24 22:11 UTC, Sheikah45 commented on migrations/v117__recommended_maps_and_mods.sql
> +    ADD COLUMN `recommended` boolean NOT NULL DEFAULT false COMMENT 'Boolean to indicate if a map is a high quality FAF Mod' AFTER `reviews`;
doh

2021-05-25 08:00 UTC, Brutus5000 requested changes
I just noticed, flyway does not pick up the file. You need a capital V in the filename.

2021-05-25 11:12 UTC, Brutus5000 approved these changes

2021-05-25 11:13 UTC, merged