Add rename permission
FAForever/db pull request #280
Opened 2021-06-05 16:26 UTC by 1-alex98

For admins or global moderators.
Tested the migration.

2021-06-05 16:29 UTC, 1-alex98 commented
```
Message    : Field 'id' doesn't have a default value
```
Why did it work on the tets server then? (I cleaned the test server up afterwards)

2021-06-06 08:47 UTC, bukajsytlos commented
I think group permissions are now managed via repeatable migrations in R__050_group_permission.sql

2021-06-06 08:48 UTC, bukajsytlos requested changes
Add it to R__050_group_permission.sql

2021-06-08 19:16 UTC, 1-alex98 commented
Repeatable migrations ???

2021-06-08 19:51 UTC, 1-alex98 commented
Execute after migration on dev/prod:
```
INSERT INTO group_permission_assignment (group_id, permission_id)
SELECT user_group.id, group_permission.id FROM user_group, group_permission
WHERE (user_group.technical_name = 'faf_moderators_global')
  AND group_permission.technical_name IN ('ROLE_ADMIN_ACCOUNT_NAME_CHANGE');

-- Server admins
INSERT INTO group_permission_assignment (group_id, permission_id)
SELECT user_group.id, group_permission.id FROM user_group, group_permission
WHERE user_group.technical_name = 'faf_server_administrators'
  AND group_permission.technical_name IN ('ROLE_ADMIN_ACCOUNT_NAME_CHANGE');

```

2021-06-08 19:54 UTC, bukajsytlos approved these changes
lgtm

2021-06-08 20:21 UTC, Brutus5000 requested changes

2021-06-08 20:21 UTC, Brutus5000 commented on migrations/R__050_group_permission.sql
> +(25,'ROLE_ADMIN_ACCOUNT_NAME_CHANGE', 'permission_group.admin_name_change')
Remove the ROLE_ prefix, that's a Spring internal thingy.
Name key misses _account part

2021-06-09 12:52 UTC, Brutus5000 approved these changes

2021-06-09 12:53 UTC, merged