Add new leaderboards and matchmaker queues for 4v4
FAForever/db pull request #290
Opened 2021-11-04 14:30 UTC by BlackYps

I also set the 1v1 unit cap to 1500.
I didn't find anything for the map pools. Are they completely managed by the moderator client?

2021-11-04 14:36 UTC, Sheikah45 commented
Yes map pools are managed by the moderator client

2021-11-04 14:37 UTC, Sheikah45 commented
Also probably want to maybe start with the disabled so they don't show to people until the map pool is ready

2021-11-04 23:14 UTC, BlackYps commented
I was thinking that we would deploy this when we want the queues to launch, but if we need the leaderboards first to set up the map pools, then yes, I can change the queues to be disabled.

2021-11-04 23:27 UTC, Sheikah45 commented
Yes you cannot set up the map pools until the queues exist

2021-11-05 00:05 UTC, Sheikah45 commented
Also here you did not add any matchmaker map pools so there will be nothing to add them to

2021-11-05 00:06 UTC, Sheikah45 commented
Actually looks like right now that is a manual brutus thing so probably need to add a flyaway for that as well

2021-11-05 11:46 UTC, BlackYps commented
I added map pool migrations. I'm not too sure if this really is a good idea, because it could lead to less flexibility when trying to manage map pools from the moderator client. Maybe @Brutus5000 can shed some light on this.

2021-11-05 11:51 UTC, Sheikah45 commented
This only controls effectively the rating range for the matchmaker brackets. Those haven't changed since we set the thing up.

The maps can still be set using the moderator client so it will not reduce flexibility.

2021-11-05 12:01 UTC, BlackYps commented
I don't understand why the build fails with Unknown column 'matchmaker_queue_id'. Am I staring at some typo that I don't see?

2021-11-05 12:10 UTC, Sheikah45 commented
You are inserting into map_pool not matchmaker_queue_map_pool

2021-11-05 13:29 UTC, Brutus5000 requested changes

2021-11-05 13:29 UTC, Brutus5000 commented on migrations/R__090_matchmaker_queue_map_pool.sql
> +INSERT INTO `matchmaker_queue_map_pool` (id, matchmaker_queue_id, map_pool_id, min_rating, max_rating) VALUES
This table is managed via API. No flyway migrations needed/allowed.

2021-11-05 13:29 UTC, Brutus5000 commented on migrations/R__080_map_pool.sql
> +INSERT INTO `map_pool` (id, name) VALUES
This table is managed via API. No flyway migrations needed/allowed.

2021-11-05 13:29 UTC, Brutus5000 commented on migrations/R__060_leaderboard.sql
> +(5,1,'tmm_4v4_share_until_death','leaderboard.tmm_4v4_share_until_death.name','leaderboard.tmm_4v4_share_until_death.description')
Why do we need 2 different leaderboards? Skill is skill?

2021-11-05 13:34 UTC, BlackYps commented on migrations/R__060_leaderboard.sql
> +(5,1,'tmm_4v4_share_until_death','leaderboard.tmm_4v4_share_until_death.name','leaderboard.tmm_4v4_share_until_death.description')
People argued that 4v4 full share and share until death are sufficiently different to warrant their own leaderboard. I'm not high rated enough to really have an informed opinion about this. I think Tagada can make the point better.

2021-11-05 14:01 UTC, Sheikah45 commented
@Brutus5000 From this https://github.com/FAForever/faf-moderator-client/issues/111#issuecomment-930515940

I took it that you wanted to just have them be managed by flyaway as well. Otherwise we may need to add the capability to the moderator client unless you just want people to do it through something like postman manually.

2021-11-05 15:19 UTC, Askaholic commented on migrations/R__070_matchmaker_queue.sql
> +(4,'tmm4v4ShareUntilDeath',0,5,'matchmaker_queue.tmm4v4ShareUntilDeath.name',4,'Share: ShareUntilDeath',0)
Imo we should stick to snake case

2021-11-05 15:20 UTC, Askaholic commented on migrations/R__070_matchmaker_queue.sql
> +(1,'ladder1v1',6,2,'matchmaker_queue.ladder1v1',1,'UnitCap: 1500',1),
Unrelated but when are we going to get rid of the ladder featured mod?

2021-11-05 20:45 UTC, BlackYps commented on migrations/R__070_matchmaker_queue.sql
> +(4,'tmm4v4ShareUntilDeath',0,5,'matchmaker_queue.tmm4v4ShareUntilDeath.name',4,'Share: ShareUntilDeath',0)
I'll have to change it in the client as well, but I forgot the names for the new leaderboards anyway, so it's not that big of a deal.

2021-11-05 20:47 UTC, Sheikah45 commented on migrations/R__070_matchmaker_queue.sql
> +(1,'ladder1v1',6,2,'matchmaker_queue.ladder1v1',1,'UnitCap: 1500',1),
I would vote just do it now

2021-11-05 20:48 UTC, Sheikah45 commented on migrations/R__070_matchmaker_queue.sql
> +(1,'ladder1v1',6,2,'matchmaker_queue.ladder1v1',1,'UnitCap: 1500',1),
I would vote just do it now

2021-11-06 22:58 UTC, Askaholic requested changes

2021-11-06 22:58 UTC, Askaholic commented on migrations/R__070_matchmaker_queue.sql
> +(4,'tmm4v4_share_until_death',0,5,'matchmaker_queue.tmm4v4_share_until_death.name',4,'Share: ShareUntilDeath',0)
Params need to be valid JSON objects. See an example here:
https://github.com/FAForever/server/blob/c9c2e47ec47b0c9545b999256587b16267cded4b/tests/data/test-data.sql#L288

2021-11-07 17:07 UTC, Brutus5000 commented
> @Brutus5000 From this [FAForever/faf-moderator-client#111 (comment)](https://github.com/FAForever/faf-moderator-client/issues/111#issuecomment-930515940)
> 
> I took it that you wanted to just have them be managed by flyaway as well. Otherwise we may need to add the capability to the moderator client unless you just want people to do it through something like postman manually.

I'm a difficult man, I don't know what I want.

2021-11-09 06:53 UTC, Askaholic approved these changes

2021-11-09 06:58 UTC, Askaholic commented
Well, my original vision was that all of this would be set up through the mod client, but I suppose unless you’re the one implementing it you can’t expect to get what you want :P. And I never had the motivation to figure out how to develop on the mod client, although I think I did attempt to set it up once.

2021-11-14 18:52 UTC, Askaholic commented on migrations/R__070_matchmaker_queue.sql
> +(1,'ladder1v1',0,2,'matchmaker_queue.ladder1v1',1,'{"GameOptions":{"UnitCap":1500}}',1),
So I guess we don’t need the unit cap here after all… hooray!

https://github.com/FAForever/fa/pull/3533

2021-11-23 23:52 UTC, BlackYps commented
Are we waiting for anything before merging this?

2021-11-26 14:48 UTC, merged

2021-11-26 14:48 UTC, Brutus5000 commented
No, I was just severely sick for 3 weeks.