Add service links table
FAForever/db pull request #294
Opened 2022-01-03 16:53 UTC by Sheikah45

2022-01-03 19:45 UTC, Askaholic commented
This will need changes in the lobby server. Even for token login the lobby server still seems to be checking the database for steamid.

2022-01-03 19:54 UTC, Sheikah45 commented
I thought the lobby server was checking steamid anymore for tokens? That was all on the user service. Because didnt we have that issue where for a short while the tokens could be used to log in without linking.

2022-01-03 20:08 UTC, Askaholic commented
I guess it doesn't enforce steam linking but it uses the presence of a steam id to determine if it can ignore the policy server result. If it can't find steam ids then people might get blocked from logging in by the policy server.

2022-01-03 20:25 UTC, Sheikah45 commented
ah gotcha, but regardless this change would just have that db call be on a separate table they are still linked by user id

2022-01-03 21:00 UTC, Brutus5000 requested changes

2022-01-03 21:00 UTC, Brutus5000 commented on migrations/V124__create_links_table.sql
> +                         `user_id` mediumint(8) unsigned NOT NULL,
Must be nullable for GDPR deletions.

2022-01-03 21:00 UTC, Brutus5000 commented on migrations/V124__create_links_table.sql
> +                         `hash_salt` char(100) NOT NULL,
This must be a global secret otherwise we can't check for existing hashes.

2022-01-03 21:00 UTC, Brutus5000 commented on migrations/V124__create_links_table.sql
> +                         `id` mediumint(8) unsigned NOT NULL AUTO_INCREMENT,
Make this a uuid instead. Auto increment makes it ordered by time and makes it possible to narrow down for which registrations this link was based on near links before and after this one.

2022-01-03 21:00 UTC, Brutus5000 commented on migrations/V124__create_links_table.sql
> +                         `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'When this entry was updated',
Delete these columns. Same reason as for id

2022-01-03 21:02 UTC, Brutus5000 commented on migrations/V124__create_links_table.sql
> +                         `hashed_id` char(256) NOT NULL,
rename to `service_id_hash`

2022-01-03 21:03 UTC, Brutus5000 commented on migrations/V124__create_links_table.sql
> +                         `service_id` varchar(100),
Add a comment: "To be set to null if account is deleted"

2022-01-03 21:05 UTC, Brutus5000 commented on migrations/V124__create_links_table.sql
> +                         `type` enum('STEAM', 'GOG', 'DISCORD', 'PATREON') COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'The service that this service id links to.',
Where do we define that this link confirms ownership? This information should not be hardcoded into the type.
I think on account deletion all links **not** related to ownership confirmation shall be deleted. So either each service link has a flag or we need a table for each type.

2022-01-04 21:26 UTC, Brutus5000 commented on migrations/V124__create_links_table.sql
> +                         `ownership` boolean,
Add a comment here:
`If true, this link confirms that the user owns FAForever. If true the link must not be delete if the linked account gets deleted. Instead keep a dangling link so the id cannot be reused.`

2022-01-06 16:09 UTC, Brutus5000 commented on migrations/V124__create_links_table.sql
> +                         `uuid` uuid unsigned NOT NULL,
uuid column should be named id.
also type uuid was just introduced with mariadb 10.7
until then use `id CHAR(36) CHARACTER SET ascii`

2022-01-16 10:42 UTC, Brutus5000 commented on migrations/V124__create_links_table.sql
> +# MIGRATION SCRIPT
You need to create the ids yourself in the migration or we set the `id` default to `UUID() `

2022-02-12 17:13 UTC, Brutus5000 commented on migrations/V124__create_links_table.sql
> +                         `id` CHAR(36) CHARACTER SET ascii NOT NULL DEFAULT UUID(),
After test I figured out that unfortunately UUID is not random at all (it's monotonic ascending). It's a UUID v1 so this implies the same problems as auto_increment.

We should remove the default and have it be populated by the application. Not sure how to fix the migration though.

2022-02-12 18:02 UTC, Sheikah45 commented on migrations/V124__create_links_table.sql
> +                         `id` CHAR(36) CHARACTER SET ascii NOT NULL DEFAULT UUID(),
Is there some field we could sort by that would be more random?

2022-07-16 15:40 UTC, Sheikah45 commented on migrations/V124__create_links_table.sql
> +                         `id` CHAR(36) CHARACTER SET ascii NOT NULL DEFAULT UUID(),
I fixed the migration script so that the uuids will be randomly ordered

2022-07-18 10:28 UTC, Brutus5000 approved these changes

2022-07-18 10:28 UTC, merged