Add coturn servers table
FAForever/db pull request #299
Opened 2022-06-17 20:02 UTC by Brutus5000

2022-06-18 06:54 UTC, Askaholic commented
Is the lobby server going to need to implement this? Or will it be handled by the API?

2022-06-18 11:38 UTC, Brutus5000 commented
API exposing the list to all clients

2022-06-20 15:06 UTC, Sheikah45 requested changes

2022-06-20 15:06 UTC, Sheikah45 commented on migrations/V124__coturn_servers.sql
> +    port          mediumint            not null,
The current coturn server have only hosts and not ports so this should be nullable

2022-06-20 15:08 UTC, Sheikah45 commented on migrations/V124__coturn_servers.sql
> +    port          mediumint            not null,
Maybe the port should just be included in the host anyway?

2022-06-21 00:58 UTC, Sheikah45 commented on migrations/V124__coturn_servers.sql
> +    port          mediumint            not null,
Also shouldn't the unique be host and port?

2022-06-23 20:09 UTC, Sheikah45 approved these changes

2022-06-23 20:11 UTC, merged