Add enum value for decapitation game mode
FAForever/db pull request #316
Opened 2024-01-12 05:45 UTC by Askaholic

Needed for https://github.com/FAForever/fa/issues/5347

Can we change the enum to be the actual string names of the victory conditions without it messing up the historical data? Seems pretty bad to me to be using stringified integers.

2024-01-12 12:35 UTC, Brutus5000 commented
According to this [SO article](https://stackoverflow.com/questions/74245365/change-column-type-and-convert-the-existing-values-from-string-to-integer-in-mar) it should work since it's only single digit.

Needs a matching change in the API, but I'm all in for cleaning types.

2024-01-12 15:48 UTC, Askaholic commented
I think simply updating the column with the new enum values would work since the index is related to the definition order. I don’t think any row updates are needed since we don’t need to change the order of the enum.

https://mariadb.com/kb/en/enum/
Funny enough, this guide specifically discourages the use of numerals as enum values because it can lead to confusing behavior and kindof defeats the purpose of using an enum in the first place.

2024-01-12 16:03 UTC, Askaholic commented on migrations/V135__add_decapitation_victory_condition.sql
> +    'DECAPITATION'
Uppercase or lowercase?

2024-01-12 16:05 UTC, Brutus5000 commented on migrations/V135__add_decapitation_victory_condition.sql
> +    'DECAPITATION'
uppercase

2024-03-25 00:06 UTC, Askaholic commented
@Brutus5000 is this good to go?

2024-04-01 19:50 UTC, Brutus5000 commented
Totally forgot about this one. I want to test this on the test server to ensure it works with server and api.

2024-04-04 15:42 UTC, Brutus5000 commented
@Askaholic short update: this breaks the API. It now always returns null for victoryCondition 😞 
Will have to figure out why.

2024-04-04 16:45 UTC, Brutus5000 commented
@Askaholic Actually the problem is different. Your change drops the values, even though it is non null.

I ran it against the test-data.sql
Before, the gameType is `0`.

After the statement it is in an inconsistent state!

```
MariaDB [faf]> select * from game_stats;
+----+---------------------+---------+--------------+----------+---------+------+-------+-----------+----------+------------------+
| id | startTime           | endTime | replay_ticks | gameType | gameMod | host | mapId | gameName  | validity | replay_available |
+----+---------------------+---------+--------------+----------+---------+------+-------+-----------+----------+------------------+
|  1 | 2024-04-04 16:42:19 | NULL    |         NULL |          |       6 |    1 |     1 | Test game |        0 |                0 |
+----+---------------------+---------+--------------+----------+---------+------+-------+-----------+----------+------------------+
1 row in set (0.000 sec)
```

2024-04-04 17:02 UTC, Askaholic commented
Ok, I’ll have to look into it more then

2024-04-12 08:58 UTC, Brutus5000 requested changes
Setting this to "changes requested" for correct status reporting

2024-04-27 23:13 UTC, Askaholic commented
Changed it to the approach described here: https://dba.stackexchange.com/questions/6547/can-i-rename-the-values-in-a-mysql-enum-column-in-one-query

I was hoping you could do the rename without having to update the rows in the table, but it does not appear to be possible without some hacky stuff. The game stats table is pretty big so it will have to update a lot of rows.

2024-04-30 08:31 UTC, Brutus5000 commented
I'm not sure if we can safely remove the old enum values ever.
I would propose to create a new nullable column `victory_condition` for the new enum.
Then update into this with a single update with case whens (multiple updates will increase the runtime I would assume).
Then make the column non-nullable and drop the old column.

2024-04-30 14:20 UTC, Askaholic commented
I'm not really sure what safety concerns you are having and how making an entirely new column would address those, but I'm also all for renaming the column to `victory_condition` as I think that's a much better name.

Were you thinking of dropping the column in a separate migration/PR?

2024-04-30 20:36 UTC, Brutus5000 commented
Because every enum member is mapped to an id, what happens if you drop the first value from the enum list? It's actually not documented. could be that all values get "shifted" because just the enum<->id mapping shifts.

Anyway. I thought about keeping the old column for potentially rolling back. But that wouldn't work because the new version of the python client would need to populate both. But if it populates both we can't remove the old column either. So let's just drop it right after. In case of a rollback we do a whole db rollback.

2024-04-30 23:40 UTC, Askaholic commented
Yes, so I actually was wondering the same thing before I made this PR and I actually tested it in my faf-db container locally with a scratch table. The ids are updated to match the order of the enum. So after the migration is complete the mapping would be:

```
DEMORALIZATION -> 1
DOMINATION -> 2
ERADICATION -> 3
SANDBOX -> 4
DECAPITATION -> 5
```

It seems that Maria will update the underlying ID values when you alter the column so that the ids match the order of the enum definition and any string values are still preserved. That’s why my first attempt at this PR didn’t work, because  the old string values were wiped away so Maria didn’t know what the int values should be and replaced them all with nulls.

2025-01-26 21:43 UTC, Brutus5000 commented
@Askaholic will this be dependent on a specific server release or is this forward/backward compatible?

2025-01-27 15:50 UTC, Askaholic commented
We’ll have to coordinate with a specific server release that also uses the new enum values.

2025-01-28 11:13 UTC, Brutus5000 commented
Well then lets do it right away, before other bigger features start blocking it again

2025-02-01 22:15 UTC, Askaholic commented
I will need a db version to be able to make a server release since our tests depend on it.

https://github.com/FAForever/server/blob/a51df6f5f5d8299952e6412b1c9aa619727d773b/.github/workflows/test.yml#L74

2025-02-02 09:19 UTC, Brutus5000 approved these changes
Will run a final test in the test environment

2025-02-02 09:19 UTC, merged